### ISSUE TITLE
Server Application Error 500

### ISSUE THREAD

**Issue by mikeboost** [yandod/candycane#241]
If any users are getting Server Application Error 500 like I was, they should consider these things:

* I failed to copy up the .htaccess file when I did scp * root@mydomain.com:~/public_html/bugs/.   I had to go back and copy that up.

* I was on a2hosting.com. They require a php.ini step for the allow_url_fopen. I followed these instructions: https://www.a2hosting.com/kb/developer-corner/php/custom-php.ini-files

* After all that, I was getting the 500 error. I had to do chmod -R 755 on ~/public_html/bugs/ to make the problem go away. That advice came from this link: http://www.zen-cart.com/showthread.php?102316-Apache-2-0-SoftException-in-Application-cpp-544-Directory-is-writeable-by-group  ...because my cPanel Apache error log kept saying "oftException in Application.cpp:601: Directory "/home/example/public_html/bugs/app/webroot" is writeable by group".

And now it's operational! :)

Now that I've done that, can you tell me what the permissions should be? I don't want to do anything risky. Or, can you share a bash script that I can run which should set the permissions the way they should?

**Comment by yandod** [comment]
Thanks for making much effort to make it works.

I have not used the hosting service you are using.
But 755 should be okay.

If you have concern about your security, you should ask somebody knows your server.
CandyCane is basically handling database and files in php way.
