### ISSUE TITLE
roadmap is not available

### ISSUE THREAD

**Issue by aviavi16** [yandod/candycane#243]
also preferences
![untitled](https://cloud.githubusercontent.com/assets/7896600/5627528/f266552a-95a1-11e4-842c-39ef61d21cf6.png)
![untitled2](https://cloud.githubusercontent.com/assets/7896600/5627529/f2671866-95a1-11e4-8276-a678c88a411e.png)

**Comment by yandod** [comment]
it seems configuration issue.
latest code works fine on our box.
http://my.candycane.jp/projects/candycane-alpha/roadmap

need more info ,and it may resolve issue on your configration.
