### ISSUE TITLE
Not receiving emails from CandyCane

### ISSUE THREAD

**Issue by kinshuksunil** [yandod/candycane#262]
My CandyCane deployment was working absolutely fine, but suddenly today (with nothing changed) it has started throwing an error message at pretty much every action inside the system. The error message is:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

I have not changed anything on the server nor in CandyCane configuration or files. Surprisingly, the action gets successfully done (eg: editing an issue might throw this error but on refreshing the issue, it is observed that the issue was successfully updated).

No idea what is happening here.

**Comment by kinshuksunil** [comment]
Okay, I figured it out.
There seems to be a problem with sending out emails via SMTP. I had enabled SMTP emails and this problem happened (my bad about me saying I hadn't changed any configuration; didn't realise this counts).

Now the problem is: I am not receiving any emails via PHP Mail, and SMTP email seems to cause unexpected errors. 

What to do?

**Comment by yandod** [comment]
CandyCane/CakePHP relies php setup when using php mail.
from application land, there is almost nothing able to do.
