### ISSUE TITLE
wikiのSidebarページが更新できない

### ISSUE THREAD

**Issue by T-Pons** [yandod/candycane#271]
redmineでは、Sidebar という名前のWikiページは特別扱いされ、
右側のbarに扱われるようですが、candycaneで なぜか無視されるようです。

**Comment by yandod** [comment]
candycaneはredime0.8からフォークしているのでそれ移行の仕様なのではないでしょうか。

**Comment by T-Pons** [comment]
なるほど。redMineの方のバージョン差分は把握してませんでした。
